[package]
name = "TweetApp"
version = "0.1.0"
authors = ["Augusto de Miranda Rodrigues"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.12.1"
